// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROG6212POE.Models;

namespace PROG6212POE.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20211128125913_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PROG6212POE.Models.HomeLogin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("PROG6212POE.Models.ModuleModel", b =>
                {
                    b.Property<int>("ModuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ClassHours")
                        .HasColumnType("REAL");

                    b.Property<double>("Credits")
                        .HasColumnType("REAL");

                    b.Property<string>("ModuleCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleName")
                        .HasColumnType("TEXT");

                    b.HasKey("ModuleID");

                    b.ToTable("ModuleInfo");
                });

            modelBuilder.Entity("PROG6212POE.Models.SelfStudyModel", b =>
                {
                    b.Property<int>("SelfStudyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateChosen")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuleChosen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModuleID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StudyHours")
                        .HasColumnType("REAL");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("SelfStudyID");

                    b.ToTable("SelfStudy");
                });

            modelBuilder.Entity("PROG6212POE.Models.WeeklySchedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FridayModule")
                        .HasColumnType("TEXT");

                    b.Property<string>("MondayModule")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThursdayModule")
                        .HasColumnType("TEXT");

                    b.Property<string>("TuesdayModule")
                        .HasColumnType("TEXT");

                    b.Property<string>("WednesdayModule")
                        .HasColumnType("TEXT");

                    b.HasKey("ScheduleID");

                    b.ToTable("Schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
