// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROG6212POE.Models;

namespace PROG6212POE.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20211125101149_SecondCreate")]
    partial class SecondCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PROG6212POE.Models.ModuleModel", b =>
                {
                    b.Property<int>("ModuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ClassHours")
                        .HasColumnType("REAL");

                    b.Property<double>("Credits")
                        .HasColumnType("REAL");

                    b.Property<string>("ModuleCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleName")
                        .HasColumnType("TEXT");

                    b.HasKey("ModuleID");

                    b.ToTable("ModuleInfo");
                });

            modelBuilder.Entity("PROG6212POE.Models.SelfStudyModel", b =>
                {
                    b.Property<int>("SelfStudyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateChosen")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuleChosen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModuleID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StudyHours")
                        .HasColumnType("REAL");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("SelfStudyID");

                    b.ToTable("SelfStudy");
                });
#pragma warning restore 612, 618
        }
    }
}
